services:
  backend:
    build: ./backend
    container_name: taskplex-backend
    ports:
      - "8000:8000"
    volumes:
      # - ./backend:/app # Désactivé pour éviter les conflits, décommentez pour le dév
      - taskplex_temp:/app/temp_files
    environment:
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000,http://localhost
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: taskplex-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  taskplex_temp:

